<?php

namespace BrainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AimlUploaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AimlUploaderRepository extends EntityRepository
{
}
