<?php

namespace BrainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AimlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AimlRepository extends EntityRepository
{
}
