brain_aiml:
    resource: "@BrainBundle/Resources/config/routing/aiml.yml"
    prefix:   /aiml

brain_homepage:
    path:     /
    defaults: { _controller: BrainBundle:Index:index }

brain_wernicke_markov:
    path:     /markov
    defaults: { _controller: BrainBundle:Wernicke:markov}
