services:
    brain.wernicke:
        class: BrainBundle\Services\Wernicke
        arguments: ["@brain.components.math", "brain.components.string"]

    brain.components.string:
        class: BrainBundle\Services\Components\StringProcessor
        arguments: []

    brain.components.math:
        class: BrainBundle\Services\Components\MathProcessor
        arguments: ["@brain.components.string"]

