services:
    brain.wernicke:
        class: BrainBundle\Services\Wernicke
        arguments: ["@brain.components.math", "brain.components.string"]

    brain.components.string:
        class: BrainBundle\Services\Components\StringProcessor
        arguments: ["@brain.components.array"]

    brain.components.math:
        class: BrainBundle\Services\Components\MathProcessor
        arguments: ["@brain.components.string"]

    brain.components.array:
        class: BrainBundle\Services\Components\ArrayProcessor
        arguments: []

    brain.aiml.upload.listener:
        class: BrainBundle\EventListener\AimlUploaderListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: vich_uploader.post_upload }