miribot_homepage:
    path:     /
    defaults: { _controller: MiribotBundle:Miribot:index }
miribot_answer:
    path:     /answer
    defaults: { _controller: MiribotBundle:Miribot:answer }

wiki:
    path:     /wiki
    defaults: { _controller: MiribotBundle:Miribot:wiki }