miribot_homepage:
    path:     /
    defaults: { _controller: MiribotBundle:Miribot:index }
miribot_answer:
    path:     /answer
    defaults: { _controller: MiribotBundle:Miribot:answer }
miribot_userdataexist:
    path:     /userdataexist
    defaults: { _controller: MiribotBundle:Miribot:userdataexist }

wiki:
    path:     /wiki
    defaults: { _controller: MiribotBundle:Miribot:wiki }