services:
  # Miribot services
  miribot:
    class: MiribotBundle\Model\Miribot
    arguments: ["@kernel", "@miribot_brain", "@helper"]

  miribot_brain:
    class: MiribotBundle\Model\Brain
    arguments: ["@graphmaster", "@helper"]

  # Helper services
  helper:
    class: MiribotBundle\Helper\Helper
    arguments: ["@kernel", "@helper_memory", "@helper_string", "@helper_template"]

  helper_string:
    class: MiribotBundle\Helper\StringHelper
    arguments: ["@kernel"]

  helper_memory:
    class: MiribotBundle\Helper\MemoryHelper
    arguments: ['miribot', '3600']

  helper_template:
    class: MiribotBundle\Helper\TemplateHelper
    arguments: ["@kernel", "@session", "@helper_memory", "@helper_string"]

  # Others
  graphmaster:
    class: MiribotBundle\Model\Graphmaster
    arguments: ["@kernel", "@helper"]
